// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQF3gl1S1Xn7qMycB_aI_ekHVQSdxrPSQ',
    appId: '1:76079204637:web:22fd79a6bc53027833b9f4',
    messagingSenderId: '76079204637',
    projectId: 'rating-app-flutter',
    authDomain: 'rating-app-flutter.firebaseapp.com',
    storageBucket: 'rating-app-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hvZPVGUveTq1ZdZC2qu0a_xPUR_-0fo',
    appId: '1:76079204637:android:d87fc30d7f6fb96833b9f4',
    messagingSenderId: '76079204637',
    projectId: 'rating-app-flutter',
    storageBucket: 'rating-app-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnXotOkeOTHnTbXtjVJha87-DvcChROjc',
    appId: '1:76079204637:ios:47245e404528dd1533b9f4',
    messagingSenderId: '76079204637',
    projectId: 'rating-app-flutter',
    storageBucket: 'rating-app-flutter.appspot.com',
    iosBundleId: 'com.example.ratingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnXotOkeOTHnTbXtjVJha87-DvcChROjc',
    appId: '1:76079204637:ios:32a9ac677ee8a25733b9f4',
    messagingSenderId: '76079204637',
    projectId: 'rating-app-flutter',
    storageBucket: 'rating-app-flutter.appspot.com',
    iosBundleId: 'com.example.ratingApp.RunnerTests',
  );
}
